shellEmulator: true

# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: accept-all

packages:
  - packages/*
  - projects/*

onlyBuiltDependencies:
  - core-js
  - edgedriver
  - esbuild
  - geckodriver
  - less
